local app=DoApp.DoApp()
app:doCommand([[NoteInput.NoteValue?LogDuration=kHemiDemiSemiQuaver]])
app:doCommand([[NoteInput.MoveAdvance]])
app:doCommand([[NoteInput.MoveAdvance]])
app:doCommand([[NoteInput.Pitch?Pitch=B]])
app:doCommand([[NoteInput.Pitch?Pitch=A]])
app:doCommand([[NoteInput.Pitch?Pitch=G]])
app:doCommand([[NoteInput.Pitch?Pitch=F]])
app:doCommand([[NoteInput.Pitch?Pitch=E]])
app:doCommand([[NoteInput.Pitch?Pitch=D]])
app:doCommand([[EventEdit.NavigateLeftExtend]])
app:doCommand([[EventEdit.NavigateLeftExtend]])
app:doCommand([[EventEdit.NavigateLeftExtend]])
app:doCommand([[EventEdit.NavigateLeftExtend]])
app:doCommand([[EventEdit.NavigateLeftExtend]])
app:doCommand([[UI.InvokePropertyChangeValue?Type=kNoteOrRestStartsVoice&Value=null: ]])
app:doCommand([[UI.InvokePropertyChangeValue?Type=kNoteOrRestEndsVoice&Value=string: "kEndImmediately"]])
app:doCommand([[UI.InvokePropertyChangeValue?Type=kEventScale&Value=string: "kGrace"]])
app:doCommand([[Window.SwitchMode?WindowMode=kEngraveMode]])
app:doCommand([[UI.InvokePropertyChangeValue?Type=kNoteHideStem&Value=string: "true"]])
app:doCommand([[Window.SwitchMode?WindowMode=kWriteMode]])
app:doCommand([[EventEdit.NavigateRight]])
app:doCommand([[EventEdit.NavigateDownExtend]])
app:doCommand([[EventEdit.NavigateLeftExtend]])
app:doCommand([[NoteInput.CreateOrnament]])
app:doCommand([[NoteInput.CreateOrnament?Definition=gliss&UseLocalOverride=0]])
