local app=DoApp.DoApp()
app:doCommand([[NoteInput.MoveLeft]])
app:doCommand([[NoteInput.Scissor]])
app:doCommand([[NoteInput.MoveLeft]])
app:doCommand([[NoteInput.Scissor]])
app:doCommand([[UI.Escape]])
app:doCommand([[NoteInput.Exit]])
app:doCommand([[EventEdit.NavigateRight]])
app:doCommand([[Edit.Delete]])
app:doCommand([[EventEdit.NavigateLeft]])
app:doCommand([[NoteInput.ForceDuration]])
app:doCommand([[NoteInput.Tie]])
