local app=DoApp.DoApp()
app:doCommand([[NoteInput.ForceDuration]])
app:doCommand([[NoteInput.Tie]])
app:doCommand([[NoteInput.SetArticulation?Value=kAccent]])
app:doCommand([[NoteInput.SetArticulation?Value=kStaccato]])
app:doCommand([[UI.InvokePropertyChangeValue?Type=kArticulationForceTieChainPosition&Value=string: "kTieChainEnd"]])
app:doCommand([[UI.InvokePropertyChangeValue?Type=kTieStyle&Value=string: "kDashed"]])
